# This file provides local caching optimizations
# It's automatically loaded by docker compose
services:
  survival-rag:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=/tmp/docker-cache
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      # Persist pip cache between builds
      - pip-cache:/root/.cache/pip
      - ./sources:/app/sources
      - ./data:/app/data

volumes:
  pip-cache:
    driver: local
